# Logger file location (will be created by browser)
# If you'd like to change default path, uncomment and provide desired log file location
# Default log file location ("must be configured in logger.py")

#logger.requests.path: "desired_log_file_path"



# If you would like to enable logger, uncomment below line and set logger.enable = "true"
# logger.enable: "true"
